name: Run PHP Tests on Pull Requests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Run PHP unit tests
        run: vendor/bin/phpunit --testdox

      - name: Cleanup (optional)
        run: echo "Cleanup tasks here"
